/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-07-01 16:42:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.food;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import db.JdbcUtil;
import vo.*;

public final class food_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/food/../_inc/incHead.jsp", Long.valueOf(1625148662000L));
    _jspx_dependants.put("/food/../_inc/incInfo.jsp", Long.valueOf(1624358560000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("db.JdbcUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");

request.setCharacterEncoding("utf-8");
String src = request.getContextPath() + "/common/";

ArrayList<FoodInfo> foodList = (ArrayList<FoodInfo>)request.getAttribute("foodList");   
PageInfo pageInfo = (PageInfo)request.getAttribute("pageInfo");   
FoodInfo foodInfo = (FoodInfo)request.getAttribute("foodInfo"); 

String pmOrder = (String)request.getAttribute("pmOrder"); 	//	 정렬에 대한 쿼리스트링 셋팅
String pmArea = (String)request.getAttribute("pmArea"); 	//	 지역에 대한 쿼리스트링 셋팅

String args = "", schargs = "";
// 검색관련 쿼리스트링 제작 
args = "?cpage=" + pageInfo.getCpage() + schargs; 
if (pageInfo.getKeyword() == null) schargs += "&keyword=";  
else schargs += "&keyword=" + pageInfo.getKeyword();


Common comm = new Common(); 

      out.write(" \r\n");
      out.write("\t  \r\n");
      out.write("<!-- content 영역 --> \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>   \r\n");
      out.write("<style> \r\n");
      out.write("body  {text-align:center;}\r\n");
      out.write("div {margin:0 auto; text-align:center;}\r\n");
      out.write("#totalList { margin:0 auto; height:100%; display:inline-block;} \r\n");
      out.write("#fdRay {display:inline-block;}\r\n");
      out.write("\r\n");
      out.write("div #top {\r\n");
      out.write("    width:100%; height:50px; text-align:center; font-size:25px; color:#4f4f4f; \r\n");
      out.write("    font-weight:bold; padding-top:30px; margin:0;\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("div #foodOrd {margin:20px auto;}\r\n");
      out.write("#ord {text-align:right;}\r\n");
      out.write("div #fdSch {width:*;  }\r\n");
      out.write("div .foodList {width:100%; display:inline-block; position:relative; height:100%;} \r\n");
      out.write("div .foodCard { position:absolute; width:100%;} \r\n");
      out.write("\r\n");
      out.write("div .br {display:block; height:30px; width:*; }\r\n");
      out.write(" \r\n");
      out.write("div #fdFilterBox {border:3px #fff solid; width:100%; font-size:14px;}\r\n");
      out.write("div .fdFilter #filterLine {display:block; } \r\n");
      out.write("div .fdFilter #fdMap {margin: 10px; display:block; }\r\n");
      out.write(".fdFilter ul li {font-size:20px;}\r\n");
      out.write(".fdFilter .fdOrdChk {margin-left:0px; float:left; margin-top:5px;}\r\n");
      out.write(".fdFilter .fdChkBox {width:15px; height:15px; }\r\n");
      out.write(".fdFilter #filterSubmit {width:40px; height:30rpx;}\r\n");
      out.write("#fdMapTitile {display:block; width:800px; }\r\n");
      out.write("div #fdOrdTitle {display:block; border:5px #4f4f4f solid;}\r\n");
      out.write("#fdFilterBox #allChk {font-weight:bold; line-height:0.5em;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("div #foodInline {display:inline-block; width:100%; margin:0 auto;} \r\n");
      out.write("div .foodBr {display:inline-block; width:100%; height:30px;}\r\n");
      out.write("\r\n");
      out.write(".outerBox {\r\n");
      out.write("    border:5px #4f4f4f solid; width:350px; height:440px; text-align:center;\r\n");
      out.write("    padding:5px; margin:10px; display:inline-block;\r\n");
      out.write("}\r\n");
      out.write(".innerBox {\r\n");
      out.write("    border:1px #000 solid; width:340px; height:435px; padding:5px; \r\n");
      out.write("    text-align:center; display:table-cell;  \r\n");
      out.write("} \r\n");
      out.write("div .foodImg { margin-top:0;}\r\n");
      out.write(".foodName { font-size:15px; padding-top:7px; padding-bottom:3px; font-weight:bold; }\r\n");
      out.write(".starRate {width:100px; height:40px;} \r\n");
      out.write(" \r\n");
      out.write("div #foodPage { width:100%;}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("function getSelectedChk() {\t// 선택한 체크박스들의 value값을 리턴하는 함수\r\n");
      out.write("\tvar idx = \"\";\t// 선택한 체크박스들의 value값을 쉼표로 구분하여 저장하는 변수\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function chkAll(all) {\r\n");
      out.write("\tvar arrChk = document.frmFood.chk;\r\n");
      out.write("\tfor (var i = 0 ; i < arrChk.length ; i++) {\r\n");
      out.write("\t\tarrChk[i].checked = all.checked;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function choose(chk) {\r\n");
      out.write("\tif (!chk.checked) {\t// 현재 체크박스를 체크 해제했을 경우\r\n");
      out.write("\t\tdocument.frmCart.all.checked = false;\r\n");
      out.write("\t}\r\n");
      out.write("} \r\n");
      out.write("function chkVal() {\r\n");
      out.write("\tvar flag = false;\r\n");
      out.write("\tvar fdVal = document.getElementByName(\"chk\");\t// 배열의 형태\r\n");
      out.write("\tSystem.out.println(\"name 밸류값 :\" +chkVal);\r\n");
      out.write("\tfor (var i = 0; i < fdVal.length; i++) {\r\n");
      out.write("\t\tif (fdVal[i].checked) {\r\n");
      out.write("\t\t\tSystem.out.println(\"name 하나이상 :\" +chkVal[i].value);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn flag;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>  \r\n");
      out.write("<input type=\"hidden\" name=\"ord\" value=\"");
      out.print(pageInfo.getOrd() );
      out.write("\" />\r\n");
      out.write("<input type=\"hidden\" name=\"area\" value=\"");
      out.print(pageInfo.getArea() );
      out.write("\" />\r\n");
      out.write("<input type=\"hidden\" name=\"psize\" value=\"");
      out.print(pageInfo.getPsize() );
      out.write("\" />\r\n");
      out.write("<div id=\"totalList\"> \r\n");
      out.write("<!-- 헤더영역 -->\r\n");
      out.write('\r');
      out.write('\n');
 
String incSrc = request.getContextPath() + "/_inc/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\"><html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(incSrc );
      out.write("/css/reset1.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(incSrc );
      out.write("/css/base1.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(incSrc );
      out.write("/css/layout1.css\" />\r\n");
      out.write(" \t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(incSrc );
      out.write("/css/main1.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t\t<h1 class=\"logo\"><a href=\"#\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_logo_150_177.png\" width=\"159\" height=\"177\" alt=\"로고\" onclick = \"location.href ='index.jsp'\" /></a></h1>\r\n");
      out.write("\t\t<ul id=\"infoMenu\">\r\n");
      out.write("\t\t\t<li><a href=\"member/join_form.jsp\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_upper_77_17_join.png\" width=\"77\" height=\"17\" alt=\"회원 가입\" class=\"hand\" onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_upper_ov_80_19_join.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_upper_77_17_join.png';\"/></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"member/mypage_form.jsp\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_upper_97_16_mypage.png\" width=\"97\" height=\"16\" alt=\"마이페이지\"  class=\"hand\"  onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_upper_ov_100_18_mypage.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_upper_97_16_mypage.png';\"/></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_upper_58_17_event.png\" width=\"58\" height=\"17\" alt=\"이벤트\"  class=\"hand\"  onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_upper_ov_61_20_event.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_upper_58_17_event.png';\"/></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_upper_77_18_center.png\" width=\"77\" height=\"18\" alt=\"고객센터\" class=\"hand\"  onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_upper_ov_81_20_center.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_upper_77_18_center.png';\"/></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul id=\"navigation\">\r\n");
      out.write("\t\t\t<li id = \"navi\"><a href=\"#\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_menu_126_27_tourInfo.png\" width=\"126\" height=\"27\" alt=\"여행 정보\" class=\"hand\" onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_menu_ov_130_29_tourInfo.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_menu_126_27_tourInfo.png';\"/></a>\t</li>\r\n");
      out.write("\t\t\t<li id = \"navi\"><a href=\"#\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_menu_57_27_hotel.png\" width=\"57\" height=\"27\" alt=\"숙박\" class=\"hand\" onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_menu_ov_60_29_hotel.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_menu_57_27_hotel.png';\"/></a></li>\r\n");
      out.write("\t\t\t<li id = \"navi\"><a href=\"#\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_menu_87_27_flight.png\" width=\"87\" height=\"27\" alt=\"항공권\" class=\"hand\" onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_menu_ov_90_29_flight.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_menu_87_27_flight.png';\"/></a></li>\r\n");
      out.write("\t\t\t<li id = \"navi\"><a href=\"#\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_menu_85_26_planner.png\" width=\"85\" height=\"26\" alt=\"플래너\" class=\"hand\" onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_menu_ov__90_26_planner.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_menu_85_26_planner.png';\"/></a></ul>\r\n");
      out.write("\t\t<ul id=\"naviSub\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_submenu_28_13_all.png\" width=\"28\" height = \"13\" alt = \"��ü\" class=\"naviSubs\"  onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_submenu_ov_31_15_all.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_submenu_28_13_all.png';\"/></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_submenu_78_14_addMem.png\" width=\"78\" height = \"14\" alt = \"동행인 구인\"  class=\"naviSubs\"onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_submenu_ov_80_15_addMem.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_submenu_78_14_addMem.png';\"/></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_submenu_78_14_makePlan.png\" width=\"78\" height = \"14\" alt = \"일정 만들기\"  class=\"naviSubs\" onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_submenu_ov_81_15_makePlan.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_submenu_78_14_makePlan.png';\"/></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_submenu_93_14_sharePlan.png\" width=\"93\" height = \"14\" alt = \"일정 공유하기\" class=\"naviSubs\" onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_submenu_ov_96_15_sharePlan.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_submenu_93_14_sharePlan.png';\"/></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(incSrc );
      out.write("/header/header_submenu_93_14_chkPlan.png\" width=\"93\" height = \"13\" alt = \"일정 확인하기\"  class=\"naviSubs\" onmouseover= \"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_submenu_ov_96_15_chkPlan.png';\" onmouseout =\"this.incSrc='");
      out.print(incSrc );
      out.write("/header/header_submenu_93_14_chkPlan.png';\"/></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>");
      out.write("  \r\n");
      out.write("<form name=\"frmFood\" action=\"\" method=\"get\">\r\n");
      out.write("\t<div id=\"fdLay\">\r\n");
      out.write("\t\t\t<p width=\"40%\"></p>  \r\n");
      out.write("\t\t<div id=\"top\">제주 음식점 추천 목록</div>  \r\n");
      out.write("\t</div> \r\n");
      out.write("\t<!-- 제주정보 이미지 -->\r\n");
      out.write('\r');
      out.write('\n');
 
String src2 = request.getContextPath() + "/common/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style> \r\n");
      out.write("div #infoInc {display:inline-block;}\r\n");
      out.write("div .tourInfoTitle {display:flex; }\r\n");
      out.write("div .infoImg {width:150px; height:100px;} \r\n");
      out.write("</style>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body> \r\n");
      out.write("\t<div id=\"infoInc\">\r\n");
      out.write("\t\t<div class=\"tourInfoTitle\">\r\n");
      out.write("\t\t\t<div class=\"infoSrc\" id=\"infoRel\">\r\n");
      out.write("\t\t\t\t<a href=\"food_list.food\" ><img src=\"");
      out.print(src2 );
      out.write("images/InfoImg/foodMain.png\" class=\"infoImg\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"infoSrc\" class=\"infoAb\">\r\n");
      out.write("\t\t\t\t<a href=\"culture_info.info\" ><img src=\"");
      out.print(src2 );
      out.write("images/InfoImg/cultMain.png\" class=\"infoImg\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"infoSrc\" class=\"infoAb\">\r\n");
      out.write("\t\t\t\t<a href=\"traffic_info.info\" ><img src=\"");
      out.print(src2 );
      out.write("images/InfoImg/trafficMain.png\" class=\"infoImg\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"infoSrc\" class=\"infoAb\">\r\n");
      out.write("\t\t\t\t<a href=\"guide_info.info\" ><img src=\"");
      out.print(src2 );
      out.write("images/InfoImg/guideMain.png\" class=\"infoImg\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>  \r\n");
      out.write("\t</div> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("\t<div class=\"br\"></div>\r\n");
      out.write("\t\t<div class=\"foodList\">   \r\n");
      out.write("\t\t\t<div align=\"right\" id=\"fdSch\">\r\n");
      out.write("\t\t\t\t<span>상호명<input type=\"text\" name=\"keyword\" value=\"");
      out.print(pageInfo.getKeyword() );
      out.write("\" />&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"submit\" value=\"식당 검색\" /> </span> \r\n");
      out.write("\t\t\t</div><br />  \r\n");
      out.write("\t\t\t<div class=\"foodCard\">\r\n");
      out.write("\t\t\t\t<!-- 필터 영역 -->\r\n");
      out.write("\t\t\t\t<div id=\"fdFilterBox\" >\r\n");
      out.write("\t\t\t\t\t<div id=\"filterLine\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"fdMapTitle\" >\r\n");
      out.write("\t\t\t\t\t\t\t<h2>지도에서 선택</h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"mapImg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.print(src );
      out.write("images/FoodImg/jejuMap.png\" usemap=\"#useJejuMap\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<map name=\"useJejuMap\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<area shape=\"poly\" coords=\"101,72,164,58,175,70,183,69,189,120,232,140,183,147,158,188,144,184,135,228,106,226,94,257,14,193,14,159,75,94\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"food_list.food?area=W");
      out.print(pmOrder );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<area shape=\"poly\" coords=\"209,40,278,26,275,36,286,40,287,57,297,68,300,95,251,138,234,144,222,130,201,126,183,101,182,68,167,68,169,58,200,47\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"food_list.food?area=N");
      out.print(pmOrder );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<area shape=\"poly\" coords=\"299,15,313,23,385,9,408,13,412,26,455,36,455,47,464,53,469,72,473,69,475,101,463,103,462,122,440,138,430,159,420,183,380,184,365,202,300,207,292,221,288,200,276,190,267,162,253,148,242,143,254,132,279,125,291,102,299,96,297,66,287,45,274,39,276,29,297,21\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"food_list.food?area=E");
      out.print(pmOrder );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<area shape=\"poly\" coords=\"144,225,137,230,165,225,197,225,201,237,228,231,256,232,280,228,291,222,289,201,279,191,278,174,271,163,256,153,247,145,214,147,200,146,184,145,173,162,158,189,148,183,140,197,139,216,136,221\"                            \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"food_list.food?area=S");
      out.print(pmOrder );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</map>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"fdMap\" class=\"fdFilter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"fdOrdTitle\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>음식점 분류</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"fdOrd\" class=\"fdFilter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"fdOrdChk\" id=\"allChk\"><input type=\"checkbox\" class=\"fdChkBox\" checked=\"checked\" name=\"all\" onclick=\"chkAll(this);\"/>&nbsp;전체선택</li><br /><br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"fdOrdChk\"><input type=\"checkbox\" class=\"fdChkBox\" name=\"chk\" value=\"KFR\" checked=\"checked\"  onclick=\"choose(this);\" />&nbsp;한식&nbsp;&nbsp;</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"fdOrdChk\"><input type=\"checkbox\" class=\"fdChkBox\" name=\"chk\" value=\"CFR\" checked=\"checked\" onclick=\"choose(this);\" />&nbsp;중식&nbsp;&nbsp;</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"fdOrdChk\"><input type=\"checkbox\" class=\"fdChkBox\" name=\"chk\" value=\"KJFR\" checked=\"checked\" onclick=\"choose(this);\" />&nbsp;향토음식&nbsp;&nbsp;</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"fdOrdChk\"><input type=\"checkbox\" class=\"fdChkBox\" name=\"chk\" value=\"JFR\" checked=\"checked\" onclick=\"choose(this);\" />&nbsp;일식&nbsp;&nbsp;</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"fdOrdChk\"><input type=\"checkbox\" class=\"fdChkBox\" name=\"chk\" value=\"WTF\" checked=\"checked\" onclick=\"choose(this);\" />&nbsp;양식&nbsp;&nbsp;</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"fdOrdChk\"><input type=\"checkbox\" class=\"fdChkBox\" name=\"chk\" value=\"CF\" checked=\"checked\" onclick=\"choose(this);\" />&nbsp;카페&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" onclick=\"chkVal();\" id=\"filterSubmit\" value=\"적 용\" /></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul> \r\n");
      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"foodOrd\">\r\n");
      out.write("\t\t\t\t\t\t\t<p id=\"ord\">정렬조건 : \r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"food_list.food");
      out.print(args);
      out.write("&ord=review_cntd");
      out.print(pmArea );
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"font-weight:");
      out.print((pageInfo.getOrd().equals("review_cntd")) ? "bold; color:blue;" : "normal" );
      out.write("\">리뷰순</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"food_list.food");
      out.print(args);
      out.write("&ord=scored");
      out.print(pmArea );
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"font-weight:");
      out.print((pageInfo.getOrd().equals("scored")) ? "bold; color:blue;" : "normal" );
      out.write("\">별점순</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"food_list.food");
      out.print(args);
      out.write("&ord=liked");
      out.print(pmArea );
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"font-weight:");
      out.print((pageInfo.getOrd().equals("liked")) ? "bold; color:blue;" : "normal" );
      out.write("\">좋아요 순</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"food_list.food");
      out.print(args);
      out.write("&ord=reg_datea");
      out.print(pmArea );
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"font-weight:");
      out.print((pageInfo.getOrd().equals("reg_datea")) ? "bold; color:blue;" : "normal" );
      out.write("\">등록일 순</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>  \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 음식점 목록 영역 -->\r\n");
      out.write("\t\t\t\t<div id=\"foodInline\">  \r\n");
      out.write("\t\t\t\t\t");
 
					if (foodList != null && foodList.size() > 0) {
					// 상품 검색결과가 있으면
						for (int i = 0 ; i < foodList.size() ; i++) {
						FoodInfo fi = foodList.get(i);  
						String lnk = "<a href=\"food_view.food" + args + "&id=" + fi.getFood_code() + 
							"&ord=" + pageInfo.getOrd() + "&psize=" + pageInfo.getPsize() + "\">"; 
							if (pageInfo.getPsize() == 9) {	// 식당목록을 한 줄에 3개씩 보여주기 
								if (i % 3 == 0)  out.println("<div class=\"foodBr\"></div>");  
					
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"outerBox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"innerBox\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"foodImg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(lnk);
      out.write("<img src=\"");
      out.print(src );
      out.write("/images/FoodImg/");
      out.print(fi.getFood_img1());
      out.write("\" width=\"335\" height=\"220\" ></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div><br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"foodName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(fi.getFood_name());
      out.write("<br /><br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"foodContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(fi.getFood_detail());
      out.write("<br /><br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t지역 : ");
      out.print(comm.getArea().get(fi.getFood_area()));
      out.write("<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t전화번호 : ");
      out.print(fi.getFood_tel() );
      out.write("<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t좋아요수 : ");
      out.print(fi.getFood_like() );
      out.write("<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t리     뷰 : ");
      out.print(fi.getFood_review_cnt() );
      out.write("<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(comm.getStar().get(Math.ceil(fi.getFood_score())) );
      out.write("\t \t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>   \r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t");
 
							}
						}
					} else {
						out.println("<tr><th>검색결과가 없습니다.</th></tr>");
					}
					
      out.write("\r\n");
      out.write("\t\t\t</div>  \r\n");
      out.write("\t\t\t<!--  페이징 영역 -->\r\n");
      out.write("\t\t\t\t");

				if (foodList != null && foodList.size() > 0) {
					args = "?ord=" + pageInfo.getOrd() + "&psize=" + pageInfo.getPsize() + schargs;
				
					out.println("<div id=\"foodPage\">");
				
					if (pageInfo.getCpage() == 1) {	// 현재 페이지 번호가 1이면
						out.println("[&lt;&lt;]&nbsp;&nbsp;[&lt;]&nbsp;&nbsp;");
					} else {
						out.print("<a href='food_list.food" + args + "&cpage=1" + "'>");
						out.println("[&lt;&lt;]</a>&nbsp;&nbsp;");
						out.print("<a href='food_list.food" + args + 
							"&cpage=" + (pageInfo.getCpage() - 1) + "'>");
						out.println("[&lt;]</a>&nbsp;&nbsp;");
					} // 첫 페이지와 이전 페이지 링크
				
					for (int i = 1, k = pageInfo.getSpage() ; i <= pageInfo.getBsize() && k <= pageInfo.getEpage() ; i++, k++) {
					// i : 루프돌릴 횟수를 검사하는 용도의 변수, k : 페이지 번호 출력용 변수
					// 조건 : bsize만큼 루프를 도는데 페이지가 마지막 페이지일 경우 bsize보다 작아도 멈춤
						if (pageInfo.getCpage() == k) {	// 현재 페이지 번호일 경우 링크없이 강조만 함
							out.print("&nbsp;<strong>" + k + "</strong>&nbsp;");
						} else {
							out.print("&nbsp;<a href='food_list.food" + args + "&cpage=" + k + "'>");
							out.print(k + "</a>&nbsp;");
						}
					} 
				
					if (pageInfo.getCpage() == pageInfo.getPcnt()) {	// 현재 페이지번호가 마지막 페이지 번호이면
						out.println("&nbsp;&nbsp;[&gt;]&nbsp;&nbsp;[&gt;&gt;]");
					} else {
						out.println("&nbsp;&nbsp;<a href='food_list.food" + args + 
							"&cpage=" + (pageInfo.getCpage() + 1) + "'>[&gt;]</a>");
						out.print("&nbsp;&nbsp;<a href='food_list.food" + args + 
							"&cpage=" + pageInfo.getPcnt() + "'>");
						out.println("[&gt;&gt;]</a>");
					}
				
					out.println("</div>");
				}
				
      out.write(" \r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>   \r\n");
      out.write("</form> \r\n");
      out.write("<script src=\"food/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script src=\"food/star.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
