/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-06-21 01:51:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.hotel;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import vo.*;
import java.util.Arrays;
import vo.*;

public final class hotel_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/admin/hotel/../_inc/incAdminLeft.jsp", Long.valueOf(1624207058000L));
    _jspx_dependants.put("/admin/hotel/../_inc/incAdminFooter.jsp", Long.valueOf(1624198132000L));
    _jspx_dependants.put("/admin/hotel/../_inc/incAdminHead.jsp", Long.valueOf(1624198132000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Arrays");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head> \r\n");
      out.write("\t<title>::: [JJRS] 관리자 :::</title>\r\n");
      out.write("\t<link href=\"../admin/common/css/default.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- wrapper -->\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<!-- header -->\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t<div class=\"session\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"user\"><span>홍길동</span>님 환영합니다.</li>\r\n");
      out.write("\t\t\t\t<!-- <li class=\"download\"><a href=\"#\">매뉴얼 다운로드</a></li> -->\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<!-- //header -->");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

 
 
String menu = ((String)request.getAttribute("menuPage") != null) ? (String)request.getAttribute("menuPage") : "";

String group1 = "hotel room reply reserve";
int gIdx = group1.indexOf(menu);
String gId = "";
if (gIdx != -1) 	gId="group-1";



      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t  window.addEventListener(\"load\", function(event) {\r\n");
      out.write("\t    console.log(\"All resources finished loading!\");\r\n");
      out.write("\r\n");
      out.write("\t\tdocument.getElementById(\"group-1\").checked = false;\r\n");
      out.write("\t\tdocument.getElementById(\"group-2\").checked = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"");
      out.print(gId);
      out.write("\").checked = true;\r\n");
      out.write("\t\t\r\n");
      out.write("\t  });\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t<!-- section -->\r\n");
      out.write("\t\t<section> \r\n");
      out.write("\t\t\t<!-- aside --> \r\n");
      out.write("\t\t\t<aside>\r\n");
      out.write("\t\t\t<h2>Admin Menu</h2>\r\n");
      out.write("\t\t\t\t<!-- side menu -->\r\n");
      out.write("\t\t\t\t<ul class=\"cd-accordion-menu animated\">\r\n");
      out.write("\t\t\t\t\t<li class=\"has-children\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"group-1\" id=\"group-1\" checked> \r\n");
      out.write("\t\t\t\t\t\t<label for=\"group-1\" class=\"sm02_01\">숙박권 리스트</label>\r\n");
      out.write("\t\t\t\t\t\t<ul>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"has-children\"><a href=\"hotel_list.hotela\" class=\"sublabel ");
      out.print((menu.equals("hotel")?"on" : ""));
      out.write("\">숙박 리스트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"has-children\"><a href=\"room_list.rooma\" class=\"sublabel ");
      out.print((menu.equals("room")?"on" : ""));
      out.write("\">방 리스트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"has-children\"><a href=\"reply_list.replya\" class=\"sublabel ");
      out.print((menu.equals("reply")?"on" : ""));
      out.write("\">후기 리스트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"has-children\"><a href=\"reserve_list.reservea\" class=\"sublabel ");
      out.print((menu.equals("reserve")?"on" : ""));
      out.write("\">숙박 예약 리스트</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"has-children\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"group-1\" id=\"group-1\" checked> \r\n");
      out.write("\t\t\t\t\t\t<label for=\"group-1\" class=\"sm02_03\">음식점 리스트</label>\r\n");
      out.write("\t\t\t\t\t\t<ul>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"has-children\"><a href=\"food_list.fooda\" class=\"sublabel on\">음식점 리스트</a></li> \r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"has-children\"><a href=\"reply_list.replya\" class=\"sublabel\">후기 리스트</a></li> \r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"has-children\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"group-2\" id=\"group-2\"> \r\n");
      out.write("\t\t\t\t\t\t<label for=\"group-2\" class=\"sm02_02\">플래너 관리</label>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"has-children\"><a href=\"#\" class=\"sublabel\">결재내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- //side menu --> \r\n");
      out.write("\t\t\t</aside> \r\n");
      out.write("\t\t\t<!-- //aside --> ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");
	@SuppressWarnings("unchecked")
	//(어노테이션) 호환되지 않은 유형으로 작동하면 프로그램이 컴파일 되지 않기에 해당 경고를 보여줌 (ArrayList 제네릭 사용시 밑줄 가리는 방법)

	// ▼▼▼ 데이터 받아와서 변수 셋팅 ▼▼▼ 
	ArrayList<HotelInfo> hotelList = (ArrayList<HotelInfo>)request.getAttribute("hotelList");
	PageInfo pageInfo = (PageInfo)request.getAttribute("pageInfo");
	Common common = new Common();

	// ▼▼▼ 검색관련 쿼리스트링 제작 ▼▼▼
	String args = "", schargs = "";
	String tmp = "";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".radio_my {\r\n");
      out.write("    display: inline-block; \r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    padding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write(".radio_my input {\r\n");
      out.write("\tmargin-top: -5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction onSubmit() {\r\n");
      out.write("\t\tvar frm = document.frm; \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (frm.sl_area.value == \"\") {\r\n");
      out.write("\t\t\talert(\"지역을 선택해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (frm.sl_type.value == \"\") {\r\n");
      out.write("\t\t\talert(\"숙박유형을 선택해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (frm.txt_name.value == \"\") {\r\n");
      out.write("\t\t\talert(\"숙박명을 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (frm.txt_zip.value == \"\") {\r\n");
      out.write("\t\t\talert(\"우편번호를 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (frm.txt_addr.value == \"\") {\r\n");
      out.write("\t\t\talert(\"주소를 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (frm.txt_tel.value == \"\") {\r\n");
      out.write("\t\t\talert(\"전화번호를 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (frm.txt_stime.value == \"\") {\r\n");
      out.write("\t\t\talert(\"체크인 시간을 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (frm.txt_etime.value == \"\") {\r\n");
      out.write("\t\t\talert(\"체크아웃 시간을 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (frm.txt_detail.value == \"\") {\r\n");
      out.write("\t\t\talert(\"상세내용을 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (frm.img_1.value == \"\") {\r\n");
      out.write("\t\t\talert(\"사진을 선택해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if(!isFileExt(frm.img_1.value)) {\r\n");
      out.write("\t\t\talert(\"'이미지1'의 파일은 jpg, gif, png, jpeg 파일만 선택 가능합니다. 다시 선택해주세요.\");\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(frm.img_2.value != \"\" && !isFileExt(frm.img_2.value)) {\r\n");
      out.write("\t\t\talert(\"'이미지2'의 파일은 jpg, gif, png, jpeg 파일만 선택 가능합니다. 다시 선택해주세요.\");\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(frm.img_3.value != \"\" && !isFileExt(frm.img_3.value)) {\r\n");
      out.write("\t\t\talert(\"'이미지3'의 파일은 jpg, gif, png, jpeg 파일만 선택 가능합니다. 다시 선택해주세요.\");\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfrm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 숫자만\r\n");
      out.write("\tfunction onlyNum(obj) {\r\n");
      out.write("\t\tif (isNaN(obj.value) == true)  {\r\n");
      out.write("\t\t\tobj.value = \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("\t// 파일확장자 확인(이미지파일 확인여부)\r\n");
      out.write("\tvar arrImg = [\"jpg\", \"gif\", \"png\", \"jpeg\"];\r\n");
      out.write("\tfunction isFileExt(str) { \r\n");
      out.write("\t\tvar arrTmp = str.split(\"\\\\\");\r\n");
      out.write("\t\tfileNameTmp =  arrTmp[arrTmp.length - 1]; \r\n");
      out.write("\t\tvar ext = str.substring(str.lastIndexOf(\".\") + 1);\r\n");
      out.write("\t\tfor (var i = 0; i < arrImg.length; i++ ) {\r\n");
      out.write("\t\t\tif (ext == arrImg[i]) return true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- article -->\r\n");
      out.write("<article>\r\n");
      out.write("\t<h3>숙박권 리스트 > 숙박 등록 폼</h3>\r\n");
      out.write("\t<!-- content -->\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- table_view -->\r\n");
      out.write("\t\t<form name=\"frm\" action=\"hotel_proc.hotela\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<div class=\"tbl_wrap_view\">\r\n");
      out.write("\t\t\t\t<table class=\"tbl_view01\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\" style=\"width:80px\">지역</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"sl_area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
 for(String key : common.getArea().keySet()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(key);
      out.write('"');
      out.write('>');
      out.print(common.getArea().get(key) );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\" style=\"width:80px\">숙박유형</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"sl_type\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
 for(String key : common.getHotelType().keySet()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(key);
      out.write('"');
      out.write('>');
      out.print(common.getHotelType().get(key) );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\" style=\"width:80px\">숙박명</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input type=\"text\" name=\"txt_name\" value=\"숙박명_테스트\"></span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr> \r\n");
      out.write("\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">우편번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input type=\"text\" name=\"txt_zip\" onkeyup=\"onlyNum(this);\" value=\"13101\"></span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">주소</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><input type=\"text\" name=\"txt_addr\" style=\"width: 460px\" value=\"제주시 주소 테스트\"></span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">전화번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input type=\"text\" name=\"txt_tel\" value=\"000-1111\"></span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">체크인</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input type=\"text\" name=\"txt_stime\" value=\"14:00\"></span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">체크아웃</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input type=\"text\" name=\"txt_etime\" value=\"11:00\"></span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">상세내용</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><textarea name=\"txt_detail\" style=\"width:770px; height:60px;\">이 호텔은 좋다.</textarea></span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">사진등록1</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"5\"><span><input type=\"file\" name=\"img_1\" style=\"width:770px;\" /></span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">사진등록2</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"5\"><span><input type=\"file\" name=\"img_2\" style=\"width:770px;\" /></span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">사진등록3</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"5\"><span><input type=\"file\" name=\"img_3\" style=\"width:770px;\" /></span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\" style=\"width:80px\">주차여부</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t    ");
 for(String key : common.getHotelParking_yn().keySet()) { 
					    	String label = common.getHotelParking_yn().get(key);
					    	String chk = (key.equals("y")) ? "checked = 'checked'" : "";
					    
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"radio_my\"> \r\n");
      out.write("\t\t\t\t\t\t\t    <input type=\"radio\" id=\"sl_park_");
      out.print(key );
      out.write("\" name=\"rdo_park_yn\" value=\"");
      out.print(key);
      out.write('"');
      out.write(' ');
      out.print(chk );
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t    <label for=\"radio1\">");
      out.print(label );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\" style=\"width:80px\">운영여부</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t");
 for(String key : common.getOpenYn().keySet()) {
					    	String label = common.getOpenYn().get(key);
					    	String chk = (key.equals("n")) ? "checked = 'checked'" : "";
					    
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"radio_my\"> \r\n");
      out.write("\t\t\t\t\t\t\t    <input type=\"radio\" id=\"sl_open_");
      out.print(key );
      out.write("\" name=\"rdo_open_yn\" value=\"");
      out.print(key);
      out.write('"');
      out.write(' ');
      out.print(chk );
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t    <label for=\"radio1\">");
      out.print(label );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t</td> \r\n");
      out.write("\t\t\t\t\t</tr> \r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- //table_view -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 버튼 -->\r\n");
      out.write("\t\t\t<div class=\"btn_wrap01_detail mgt25\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" onclick=\"onSubmit();\" class=\"btn_big blue\">등록</a>\r\n");
      out.write("\t\t\t\t<a href=\"hotel_list.hotela\" class=\"btn_big\">목록</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- //버튼 -->\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //content -->\r\n");
      out.write("\r\n");
      out.write("</article>\r\n");
      out.write("<!-- //article -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<!-- //section -->\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<footer>copyright</footer>\r\n");
      out.write("<!-- //footer -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //wrapper -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
