/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-06-20 14:22:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.food;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import db.JdbcUtil;
import vo.*;

public final class food_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/food/../_inc/incHead.jsp", Long.valueOf(1624198132000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("db.JdbcUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("utf-8");

ArrayList<FoodInfo> foodList = (ArrayList<FoodInfo>)request.getAttribute("foodList");   
PageInfo pageInfo = (PageInfo)request.getAttribute("pageInfo");   
FoodInfo foodInfo = (FoodInfo)request.getAttribute("foodInfo"); 

String args = "", schargs = "";
// 검색관련 쿼리스트링 제작 
args = "?cpage=" + pageInfo.getCpage() + schargs;
if (pageInfo.getKeyword() == null)	schargs += "&keyword=";
else		schargs += "&keyword=" + pageInfo.getKeyword(); 

String src = request.getContextPath() + "/common/images/InfoImg/";

      out.write(" \r\n");
      out.write("\t  \r\n");
      out.write("<!-- content 영역 --> \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"common/css/form.css?alter\"> \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"common/css/button.css?alter\"> \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"common/css/default.css?alter\">    \r\n");
      out.write("  \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>   \r\n");
      out.write("<style> \r\n");
      out.write("div {margin:0 auto; text-align:center;}\r\n");
      out.write("#totalList {width:1180px; margin:0 auto; height:100%; display:inline-block;} \r\n");
      out.write("#fdRay {display:inline-block;}\r\n");
      out.write("\r\n");
      out.write("div #top {\r\n");
      out.write("    width:100%; height:50px; text-align:center; font-size:25px; color:#4f4f4f; \r\n");
      out.write("    font-weight:bold; padding-top:30px; margin:0;\t\r\n");
      out.write("\t}\r\n");
      out.write("div #infoInc {display:inline-block;}\r\n");
      out.write("\r\n");
      out.write("div #foodOrd {text-align:right; marin:0 auto;}\r\n");
      out.write("div #fdSch {width:*;  }\r\n");
      out.write("div .foodList {width:100%; display:inline-block; position:relative; height:100%;} \r\n");
      out.write("div .foodCard { position:absolute; width:100%;} \r\n");
      out.write("\r\n");
      out.write("div .br {display:block; height:30px; width:*; }\r\n");
      out.write("\r\n");
      out.write("div .fdFilter {display:inline-block;} \r\n");
      out.write("div #fdFilterBox {width:250px; height:1000px; border:3px; left:0; position:absolute;}\r\n");
      out.write("div .fdFilter #filterLine {display:block;} \r\n");
      out.write("div .fdFilter #fdMap {margin: 10px; display:block; }\r\n");
      out.write("\r\n");
      out.write("#fdMapTitile {display:block;}\r\n");
      out.write("div #fdOrdTitle {display:block; border:5px #4f4f4f solid;}\r\n");
      out.write("\r\n");
      out.write("div #foodInline {display:inline-block; width:100%; margin-left:100px}\r\n");
      out.write("div .foodBr {display:inline-block; width:100%; height:30px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".outerBox {\r\n");
      out.write("    border:5px #4f4f4f solid; width:240px; text-align:center;\r\n");
      out.write("    padding:5px; margin:10px; display:inline-block;\r\n");
      out.write("}\r\n");
      out.write(".innerBox {\r\n");
      out.write("    border:1px #000 solid; width:230px; height:190px; padding:5px; \r\n");
      out.write("    text-align:center; display:table-cell; vertical-align:middle;\r\n");
      out.write("}\r\n");
      out.write(".foodName { font-size:15px; padding-top:7px; padding-bottom:3px; font-weight:bold; }\r\n");
      out.write(" \r\n");
      out.write("div .tourInfoTitle {display:flex; }\r\n");
      out.write("div .infoImg {width:150px; height:100px;} \r\n");
      out.write("div #foodPage { width:100%;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>  \r\n");
      out.write("<input type=\"hidden\" name=\"ord\" value=\"");
      out.print(pageInfo.getOrd() );
      out.write("\" />\r\n");
      out.write("<input type=\"hidden\" name=\"psize\" value=\"");
      out.print(pageInfo.getPsize() );
      out.write("\" />\r\n");
      out.write("<div id=\"totalList\"> \r\n");
      out.write("<!-- 헤더영역 -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/reset1.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/base1.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/layout1.css\" />\r\n");
      out.write(" \t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main1.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<h1 class=\"logo\"><a href=\"#\"><img src=\"header/header_logo_150_177.png\" width=\"159\" height=\"177\" alt=\"로고\" /></a></h1>\r\n");
      out.write("\t\t<ul id=\"infoMenu\">\r\n");
      out.write("\t\t\t<li><img src=\"header/header_upper_77_17_join.png\" width=\"77\" height=\"17\" alt=\"회원 가입\"  onmouseover= \"this.src='header/header_upper_ov_80_19_join.png';\" onmouseout =\"this.src='header/header_upper_77_17_join.png';\"/></li>\r\n");
      out.write("\t\t\t<li><img src=\"header/header_upper_97_16_mypage.png\" width=\"97\" height=\"16\" alt=\"마이페이지\"  onmouseover= \"this.src='header/header_upper_ov_100_18_mypage.png';\" onmouseout =\"this.src='header/header_upper_97_16_mypage.png';\"/></li>\r\n");
      out.write("\t\t\t<li><img src=\"header/header_upper_58_17_event.png\" width=\"58\" height=\"17\" alt=\"이벤트\"  onmouseover= \"this.src='header/header_upper_ov_61_20_event.png';\" onmouseout =\"this.src='header/header_upper_58_17_event.png';\"/></li>\r\n");
      out.write("\t\t\t<li><img src=\"header/header_upper_77_18_center.png\" width=\"77\" height=\"18\" alt=\"고객센터\" onmouseover= \"this.src='header/header_upper_ov_81_20_center.png';\" onmouseout =\"this.src='header/header_upper_77_18_center.png';\"/></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul id=\"navigation\">\r\n");
      out.write("\t\t\t<li id = \"navi\"><a href=\"#\"><img src=\"header/header_menu_126_27_tourInfo.png\" width=\"126\" height=\"27\" alt=\"여행 정보\" class=\"hand\" onmouseover= \"this.src='header/header_menu_ov_130_29_tourInfo.png';\" onmouseout =\"this.src='header/header_menu_126_27_tourInfo.png';\"/></a>\t</li>\r\n");
      out.write("\t\t\t<li id = \"navi\"><a href=\"#\"><img src=\"header/header_menu_57_27_hotel.png\" width=\"57\" height=\"27\" alt=\"숙박\" class=\"hand\" onmouseover= \"this.src='header/header_menu_ov_60_29_hotel.png';\" onmouseout =\"this.src='header/header_menu_57_27_hotel.png';\" /></a></li>\r\n");
      out.write("\t\t\t<li id = \"navi\"><a href=\"#\"><img src=\"header/header_menu_87_27_flight.png\" width=\"87\" height=\"27\" alt=\"항공권\" class=\"hand\" onmouseover= \"this.src='header/header_menu_ov_90_29_flight.png';\" onmouseout =\"this.src='header/header_menu_87_27_flight.png';\" /></a></li>\r\n");
      out.write("\t\t\t<li id = \"navi\"><a href=\"#\"><img src=\"header/header_menu_85_26_planner.png\" width=\"85\" height=\"26\" alt=\"플래너\" class=\"hand\" onmouseover= \"this.src='header/header_menu_ov__90_26_planner.png';\" onmouseout =\"this.src='header/header_menu_85_26_planner.png';\" /></a></ul>\r\n");
      out.write("\t\t\t<ul id=\"naviSub\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><img src=\"header/header_submenu_28_13_all.png\" width=\"28\" height = \"13\" alt = \"전체\" class=\"naviSubs\"  onmouseover= \"this.src='header/header_submenu_ov_31_15_all.png';\" onmouseout =\"this.src='header/header_submenu_28_13_all.png';\"/></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><img src=\"header/header_submenu_78_14_addMem.png\" width=\"78\" height = \"14\" alt = \"동행자 구인\"  class=\"naviSubs\"onmouseover= \"this.src='header/header_submenu_ov_80_15_addMem.png';\" onmouseout =\"this.src='header/header_submenu_78_14_addMem.png';\"/></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><img src=\"header/header_submenu_78_14_makePlan.png\" width=\"78\" height = \"14\" alt = \"일정 만들기\"  class=\"naviSubs\" onmouseover= \"this.src='header/header_submenu_ov_81_15_makePlan.png';\" onmouseout =\"this.src='header/header_submenu_78_14_makePlan.png';\"/></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><img src=\"header/header_submenu_93_14_sharePlan.png\" width=\"93\" height = \"14\" alt = \"일정 공유하기\" class=\"naviSubs\" onmouseover= \"this.src='header/header_submenu_ov_96_15_sharePlan.png';\" onmouseout =\"this.src='header/header_submenu_93_14_sharePlan.png';\"/></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><img src=\"header/header_submenu_93_14_chkPlan.png\" width=\"93\" height = \"13\" alt = \"일정 확인하기\"  class=\"naviSubs\" onmouseover= \"this.src='header/header_submenu_ov_96_15_chkPlan.png';\" onmouseout =\"this.src='header/header_submenu_93_14_chkPlan.png';\"/></a></li></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("  \r\n");
      out.write("<form name=\"frmFood\" action=\"\" method=\"get\">\r\n");
      out.write("\t<div id=\"fdLay\">\r\n");
      out.write("\t\t<div id=\"cata\">분류</div>\r\n");
      out.write("\t\t\t<p width=\"40%\"></p>  \r\n");
      out.write("\t\t<div id=\"top\">제주 음식점 추천 목록</div> \r\n");
      out.write("\t\t\t<div id=\"foodOrd\">\r\n");
      out.write("\t\t\t\t<p style >정렬조건 : \r\n");
      out.write("\t\t\t\t\t<a href=\"food_list.food");
      out.print(args);
      out.write("&psize=9\">\r\n");
      out.write("\t\t\t\t\t<img src=\"food/../common/images/PublisingImg/icon_list.png\" width=\"15\" align=\"absmiddle\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>   \r\n");
      out.write("\t</div> \r\n");
      out.write("\t<div id=\"infoInc\">\r\n");
      out.write("\t\t<div class=\"tourInfoTitle\">\r\n");
      out.write("\t\t\t<div class=\"infoSrc\" id=\"infoRel\">\r\n");
      out.write("\t\t\t\t<a href=\"food_list.food\" ><img src=\"");
      out.print(src );
      out.write("foodMain.png\" class=\"infoImg\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"infoSrc\" class=\"infoAb\">\r\n");
      out.write("\t\t\t\t<a href=\"culture_info.info\" ><img src=\"");
      out.print(src );
      out.write("cultMain.png\" class=\"infoImg\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"infoSrc\" class=\"infoAb\">\r\n");
      out.write("\t\t\t\t<a href=\"traffic_info.info\" ><img src=\"");
      out.print(src );
      out.write("trafficMain.png\" class=\"infoImg\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"infoSrc\" class=\"infoAb\">\r\n");
      out.write("\t\t\t\t<a href=\"guide_info.info\" ><img src=\"");
      out.print(src );
      out.write("guideMain.png\" class=\"infoImg\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>  \r\n");
      out.write("\t</div> \r\n");
      out.write("\t<div class=\"br\"></div>\r\n");
      out.write("\t\t<div class=\"foodList\">   \r\n");
      out.write("\t\t\t<div align=\"right\" id=\"fdSch\">\r\n");
      out.write("\t\t\t\t<span>상호명<input type=\"text\" name=\"keyword\" value=\"");
      out.print(pageInfo.getKeyword() );
      out.write("\" />&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"submit\" value=\"식당 검색\" /> </span> \r\n");
      out.write("\t\t\t</div><br />  \r\n");
      out.write("\t\t\t<div class=\"foodCard\">\r\n");
      out.write("\t\t\t\t<div id=\"fdFilterBox\" >\r\n");
      out.write("\t\t\t\t\t<div id=\"filterLine\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"fdMapTitle\" >\r\n");
      out.write("\t\t\t\t\t\t\t<h2>지도에서 선택</h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"fdMap\" class=\"fdFilter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"fdOrdTitle\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>음식점 분류</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"fdOrd\" class=\"fdFilter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"fdOrdBox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"fdOrdChk\"><input type=\"checkbox\" />한식\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"foodInline\">\r\n");
      out.write("\t\t\t\t\t");

					// 지역 이름 comm
					Common comm = new Common(); 
					if (foodList != null && foodList.size() > 0) {
					// 상품 검색결과가 있으면
						for (int i = 0 ; i < foodList.size() ; i++) {
						FoodInfo fi = foodList.get(i);  
						String lnk = "<a href=\"food_view.food" + args + "&id=" + fi.getFood_code() + 
							"&ord=" + pageInfo.getOrd() + "&psize=" + pageInfo.getPsize() + "\">"; 
							if (pageInfo.getPsize() == 9) {	// 식당목록을 한 줄에 3개씩 보여주기 
								if (i % 3 == 0)  out.println("<div class=\"foodBr\"></div>");  
				
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"outerBox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"innerBox\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(lnk);
      out.write("<img src=\"food/../common/images/FoodImg/");
      out.print(fi.getFood_img1());
      out.write("\" width=\"225\" height=\"200\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div><br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"foodName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(fi.getFood_name());
      out.write("<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"foodContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(fi.getFood_detail());
      out.write("<br /> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t지역 : ");
      out.print(comm.getArea().get(fi.getFood_area()) );
      out.write("<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>   \r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t");
 
							}
						}
					} else {
						out.println("<tr><th>검색결과가 없습니다.</th></tr>");
					}
						
      out.write("   \r\n");
      out.write("\t\t\t</div>  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

				if (foodList != null && foodList.size() > 0) {
					args = "?ord=" + pageInfo.getOrd() + "&psize=" + pageInfo.getPsize() + schargs;
				
					out.println("<div id=\"foodPage\">");
				
					if (pageInfo.getCpage() == 1) {	// 현재 페이지 번호가 1이면
						out.println("[&lt;&lt;]&nbsp;&nbsp;[&lt;]&nbsp;&nbsp;");
					} else {
						out.print("<a href='food_list.food" + args + "&cpage=1" + "'>");
						out.println("[&lt;&lt;]</a>&nbsp;&nbsp;");
						out.print("<a href='food_list.food" + args + 
							"&cpage=" + (pageInfo.getCpage() - 1) + "'>");
						out.println("[&lt;]</a>&nbsp;&nbsp;");
					} // 첫 페이지와 이전 페이지 링크
				
					for (int i = 1, k = pageInfo.getSpage() ; i <= pageInfo.getBsize() && k <= pageInfo.getEpage() ; i++, k++) {
					// i : 루프돌릴 횟수를 검사하는 용도의 변수, k : 페이지 번호 출력용 변수
					// 조건 : bsize만큼 루프를 도는데 페이지가 마지막 페이지일 경우 bsize보다 작아도 멈춤
						if (pageInfo.getCpage() == k) {	// 현재 페이지 번호일 경우 링크없이 강조만 함
							out.print("&nbsp;<strong>" + k + "</strong>&nbsp;");
						} else {
							out.print("&nbsp;<a href='food_list.food" + args + "&cpage=" + k + "'>");
							out.print(k + "</a>&nbsp;");
						}
					} 
				
					if (pageInfo.getCpage() == pageInfo.getPcnt()) {	// 현재 페이지번호가 마지막 페이지 번호이면
						out.println("&nbsp;&nbsp;[&gt;]&nbsp;&nbsp;[&gt;&gt;]");
					} else {
						out.println("&nbsp;&nbsp;<a href='food_list.food" + args + 
							"&cpage=" + (pageInfo.getCpage() + 1) + "'>[&gt;]</a>");
						out.print("&nbsp;&nbsp;<a href='food_list.food" + args + 
							"&cpage=" + pageInfo.getPcnt() + "'>");
						out.println("[&gt;&gt;]</a>");
					}
				
					out.println("</div>");
				}
				
      out.write(" \r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>  \r\n");
      out.write("</form> \r\n");
      out.write("<script src=\"food/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script src=\"food/star.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
